### list users
GET {{users}}
Content-Type: application/json

### get a user
GET {{users}}/1
Content-Type: application/json

### create a user
POST {{users}}
Content-Type: application/json

{
    "name": "dev",
    "email": "dev@mail"
}

### put a user
PUT {{users}}/1
Content-Type: application/json

{
    "name": "dev",
    "email": "dev@mail"
}

### delete user
DELETE {{users}}/2